Missing third argument in invalidate event
sqlalchemy/sqlalchemy-collectd pull request #11
Opened 2021-07-15 07:44 UTC by kulaginds

On our company private repository raised exception like below:
`Traceback (most recent call last):
  File "auth_api.py", line 169, in current_user
                      .filter_by(email=email.lower())
  File "sqlalchemy/orm/query.py", line 3429, in first
              ret = list(self[0:1])
  File "sqlalchemy/orm/query.py", line 3203, in __getitem__
                  return list(res)
  File "sqlalchemy/orm/query.py", line 3535, in __iter__
          return self._execute_and_instances(context)
  File "sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
          result = conn.execute(querycontext.statement, self._params)
  File "sqlalchemy/engine/base.py", line 1011, in execute
              return meth(self, multiparams, params)
  File "sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
              return connection._execute_clauseelement(self, multiparams, params)
  File "sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
              distilled_params,
  File "sqlalchemy/engine/base.py", line 1317, in _execute_context
                  e, statement, parameters, cursor, context
  File "sqlalchemy/engine/base.py", line 1523, in _handle_dbapi_exception
                          self.engine.pool._invalidate(dbapi_conn_wrapper, e)
  File "sqlalchemy/pool/base.py", line 326, in _invalidate
              connection.invalidate(exception)
  File "sqlalchemy/pool/base.py", line 988, in invalidate
              self._connection_record.invalidate(e=e, soft=soft)
  File "sqlalchemy/pool/base.py", line 572, in invalidate
              self.__pool.dispatch.invalidate(self.connection, self, e)
  File "sqlalchemy/event/attr.py", line 322, in __call__
              fn(*args, **kw)
TypeError: _invalidate_evt() takes 3 positional arguments but 4 were given`

I found documentation about events invalidate and soft_invalidate and add third argument exception to `EngineCollector._invalidate_evt` function.
https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.PoolEvents.invalidate
https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.PoolEvents.soft_invalidate

2021-07-15 09:43 UTC, kulaginds commented
@zzzeek, @jvanasco, @uralbash can you review this PR?
I'm sorry for additional mention, if notification about this pull request already sent on creating this PR.

2021-07-15 12:10 UTC, zzzeek commented
@kulaginds your company is actually using sqlalchemy-collectd?   I didnt think anyone actually used this :)   I will have a look later today.

2021-07-15 13:35 UTC, kulaginds commented
@zzzeek I made adapter for integrate this solution (client) to work with Prometheus. In future I've finish preparing my repo https://github.com/kulaginds/sqlalchemy-prometheus to use it in open source community. But not now.

Thank's for your attention.

2021-07-15 14:34 UTC, jvanasco commented
This LGTM as a quick fix for a minor bump. It just adds a missing arg.

The concerns I have for long-term:

1. does this require changing a minimum version for sqlalchemy?    it looks like the event was initially added in the .9 release but updated within that release cycle to have the exc arg   see 1.0 and 0.9 tags

  * https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_0/lib/sqlalchemy/events.py#L416
  * https://github.com/sqlalchemy/sqlalchemy/blob/rel_0_9/lib/sqlalchemy/events.py#L370

2. should all the events be audited for compliance?
3. tests?

2021-07-15 19:01 UTC, zzzeek commented
the real bug here is that there are no tests for the "collector" module and that's why this regression wasn't noticed.   do you have any interest in writing up a new suite sqlalchemy_collectd/client/tests/test_collector.py?   otherwise I can work on this.

2021-07-15 19:02 UTC, zzzeek requested changes
let me know if there's an interest in writing tests.  as this is an important issue, I can work on these if you don't plan to.

2021-07-16 12:57 UTC, kulaginds commented
I trying to write test on this bug in weekends.

2022-01-06 11:16 UTC, charlotteburki-conser commented
Hi,
We are also using sqlalchemy-collectd and have the same problem. Are they any update on this issue? Is there something we can do to help fix this issue, i.e are you waiting for tests to be written before accepting the pull request?

2022-01-06 13:34 UTC, zzzeek commented
OK this is a big problem with PRs, looking at the comments, I was ready to work on this if needed, someone was going to work on it, so likely at that moment this whole issue was 100% erased for me since I deal with a dozen issues daily, and it was all in July.  OK.    I dont see any other issues in my inbox so let me try to motor out something minimal for this right now.

2022-01-06 13:35 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d9600e19073c852d4445e5977c985be5687b66d1 of this pull request into gerrit so we can run tests and reviews and stuff

2022-01-06 13:35 UTC, sqla-tester commented
New Gerrit review created for change d9600e19073c852d4445e5977c985be5687b66d1: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy-collectd/+/3490

2022-01-06 14:10 UTC, charlotteburki-conser commented
Great, thanks!

2022-01-06 14:18 UTC, sqla-tester commented
**Dmitry Kulagin** has proposed a fix for this issue in the **main** branch:

**Missing third argument in invalidate event** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy-collectd/+/3490

2022-01-06 14:28 UTC, zzzeek commented
I'm going to release this as sqlalchemy-collectd 0.0.8 and then quickly do another 0.1.0 release that will bring the codebase to minimum py36.   Looking at pypi download stats it seems we have py36 downloads but nothing before (no python 2, etc.)

2022-01-06 14:29 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy-collectd/+/3490

2022-01-06 14:32 UTC, sqla-tester commented
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy-collectd/+/3490

2022-01-06 14:34 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy-collectd/+/3490 has been **merged**. Congratulations! :)

2022-01-06 14:35 UTC, closed without merging

2022-01-06 14:54 UTC, zzzeek commented
This is released at https://pypi.org/project/sqlalchemy-collectd/0.0.8/ .  hopefully this fixes everything for you.   going to set min python version to 3.6 for next release.

2022-01-06 14:55 UTC, zzzeek commented
also supporting sqlalchemy 1.3 or higher.   1.2  / 1.1 will still work in the short term but will be removed from test support.

2022-01-06 15:54 UTC, charlotteburki-conser commented
Great, thanks. I will test it now.